name: 1d-verifications
channels:
  - conda-forge
  - pyomeca
dependencies:
  - python
  - dash=1.4.0
  - dash-renderer=1.1.1
  - dash-core-components=1.3.0
  - dash-html-components=1.0.1
  - plotly=4.1.1
  - numpy=1.17.2
  - pandas=0.25.1
  - pyomeca=2019.8.1
  - pyosim
