name: 1d-verifications
channels:
  - defaults
  - conda-forge
  - pyomeca
dependencies:
  - python
  - dash
  - dash-renderer
  - dash-core-components
  - dash-html-components
  - plotly
  - numpy
  - pandas
  - pyomeca
  - pyosim

